export const BASE_URL = 'http://138.197.102.70/api';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const LOADING_CATEGORIES = 'LOADING_CATEGORIES';
export const ERROR_CATEGORIES = 'ERROR_CATEGORIES';
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_MATERIALS = 'SET_MATERIALS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
